# Generated by Django 3.2.4 on 2021-06-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('black_list', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Url',
                'verbose_name_plural': 'Urls',
                'db_table': 'urls',
            },
        ),
    ]
