# Generated by Django 3.2.4 on 2021-06-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_url_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='title',
        ),
    ]
