# Generated by Django 3.2.4 on 2021-06-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_auto_20210607_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='surname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
