# Generated by Django 3.2.4 on 2021-06-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_auto_20210617_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='is_pub_black',
        ),
        migrations.RemoveField(
            model_name='url',
            name='is_pub_black',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_pub_black',
        ),
    ]
